[build]
  functions = "netlify/functions"

# Konfigurasi untuk semua functions
[functions]
  node_bundler = "esbuild"
  included_files = ["!node_modules/@sparticuz/chromium/bin/**"]

# Konfigurasi SPESIFIK untuk function generate-pdf
# Menambahkan timeout dan alokasi memori
[functions."generate-pdf"]
  timeout = 26
  memory = 1024

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
